587 proposition for sfx countdown right before the match ends
JanSeliv/Bomber pull request #55
Opened 2022-12-16 05:37 UTC by h4rdmol

![image](https://user-images.githubusercontent.com/5227233/208029700-f6e21ff7-b3e3-4db0-b28f-a37b6b1cec7e.png)

![image](https://user-images.githubusercontent.com/5227233/208029728-778b6bb0-7005-4c09-9166-965c888bd41b.png)

2022-12-16 05:37 UTC, h4rdmol commented
![image](https://user-images.githubusercontent.com/5227233/208029794-a5cf4821-b8b0-46d4-8d68-cd8bb3064f81.png)

2022-12-16 19:43 UTC, JanSeliv requested changes
Thank you for PR, I left some comments, let's please address them before we submit the changes

2022-12-16 19:43 UTC, JanSeliv commented on Source/Bomber/Private/GameFramework/MyGameStateBase.cpp
> +#include "SoundsManager.h"
It's rather minor and I feel uncomfortable to say it, but could you please move this include up , to the group above //---, where all includes from the project are added

2022-12-16 19:43 UTC, JanSeliv commented on Source/Bomber/Private/GameFramework/MyGameStateBase.cpp
> +			if(FMath::IsNearlyEqual(InGameTimerSecRemainInternal, 10.0f, UGameStateDataAsset::Get().GetTickInterval() - 0.01f))
Another minor, please format the code to have space between 'if' and its condition: if\[space\](condition)

2022-12-16 19:43 UTC, JanSeliv commented on Source/Bomber/Private/GameFramework/MyGameStateBase.cpp
> +				SoundsManager->PlayEndGameCountdownSFX();
Could you please wrap this condition by braces according to Epic's coding standard ([link](https://docs.unrealengine.com/5.1/en-US/epic-cplusplus-coding-standard-for-unreal-engine/)) - 'braces' category

2022-12-16 19:43 UTC, JanSeliv commented on Source/Bomber/Private/GameFramework/MyGameStateBase.cpp
> +			if(FMath::IsNearlyEqual(InGameTimerSecRemainInternal, 10.0f, UGameStateDataAsset::Get().GetTickInterval() - 0.01f))
it would be fine to put such hardcoded value 10.0f to constexpr to let others know what is the purpose. I would recommend you to make any hardcoded values as constexpr if we don't want to make it as UPROPERTY.
constexpr SoundDuration = 10.f;

2022-12-16 19:43 UTC, JanSeliv commented on Source/Bomber/Private/GameFramework/MyGameStateBase.cpp
> +			if(FMath::IsNearlyEqual(InGameTimerSecRemainInternal, 10.0f, UGameStateDataAsset::Get().GetTickInterval() - 0.01f))
0.01f could be replaced by Epic's macro KINDA_SMALL_NUMBER. Also, let's also others know what is 'UGameStateDataAsset::Get().GetTickInterval() - 0.01f' making it as regular local variable above condition:
const float Tolerance = UGameStateDataAsset::Get().GetTickInterval() - KINDA_SMALL_NUMBER;

2022-12-16 19:43 UTC, JanSeliv commented on Source/Bomber/Public/SoundsManager.h
> +	FORCEINLINE class USoundBase* GetEndGameCountdownSFX() const { return EndGameCountdownSFXInternal; }
for last revisions, class predefinition ('class USoundBase;') is already defined above the file, so you can remove the '**class**' here:
FORCEINLINE **\[NoClassThere\]** USoundBase* Getblabla...

2022-12-16 19:43 UTC, JanSeliv commented on Source/Bomber/Public/SoundsManager.h
> -	TObjectPtr<USoundBase> ExplosionSFXInternal = nullptr;
Revert this part of code you changed:
1. Notice, you removed 'ExplosionSFXInternal' variable, so the project **will not compile anymore,** probably it happened because bad merge on your side
2. Please remove extra space you added between comment and property of ItemPickUpSFXInternal
![image](https://user-images.githubusercontent.com/20540872/208174893-851a0b83-7c78-423e-a08b-c8f3e3bbe817.png)

2022-12-16 19:43 UTC, JanSeliv commented on Source/Bomber/Public/SoundsManager.h
> +	TObjectPtr<class USoundBase> EndGameCountdownSFXInternal = nullptr; //[D]
1. Please remove the '**class**' here only because it's already defined above:
2. Please remove the **//[D]** property tag, I just removed last week all such tags from code everywhere to not support them anymore.
TObjectPtr<**\[1NoClassThere]** USoundBase> EndGameCountdownSFXInternal = nullptr; **\[2No//[D]There\]**

2022-12-16 19:54 UTC, JanSeliv commented on Source/Bomber/Private/GameFramework/MyGameStateBase.cpp
> +		/** to do: adjust the value of 10.0f to match the duration of the file from meta sound. */
Let's make 'to do' more informative
- Replace '**to do**' with **'@TODO'**, so you will see it with any IDE in 'todo' window.
- Add your name h4rdmol, so we will see who is owner of that todo.
- Add Trello ID, so we will not forget about card.
@TODO h4rdmol baYkHels Adjust hardcoded value to match the duration of the EndGame SFX from meta sound

2022-12-17 01:07 UTC, h4rdmol commented on Source/Bomber/Public/SoundsManager.h
> -	TObjectPtr<USoundBase> ExplosionSFXInternal = nullptr;
it's really weird that it happened. Sorry for that.

2022-12-17 02:10 UTC, h4rdmol commented
@JanSeliv many thanks for the review.  All comments are resolved with the latest commit thank you!

2022-12-17 03:02 UTC, JanSeliv requested changes
'This branch cannot be rebased due to conflicts': please solve conflicts

2022-12-17 03:02 UTC, JanSeliv commented on Source/Bomber/Public/SoundsManager.h
> +	UFUNCTION(BlueprintCallable, BlueprintPure, Category = "C++")
Please Remove BlueprintCallable there. According Epic's documentation, 'BlueprintPure' (that is used for const functions) already exposes the function to blueprints. You can notice, const-function above does not use BlueprintCallable anymore

2022-12-17 03:13 UTC, closed without merging