Added data assest with BT
JanSeliv/Bomber pull request #60
Opened 2022-12-31 17:15 UTC by h4rdmol

2022-12-31 17:16 UTC, h4rdmol commented
![image](https://user-images.githubusercontent.com/5227233/210150972-35530fb1-de2e-41c4-aeb6-f001e81ba2c1.png)
![image](https://user-images.githubusercontent.com/5227233/210150978-9fec3c5e-c48e-48b4-961b-af5ee0c5c231.png)
![image](https://user-images.githubusercontent.com/5227233/210150985-834ba25e-45da-4083-8193-8b9f768ca93d.png)

2023-01-01 16:23 UTC, JanSeliv reviewed
I see, we have 'BB_NewAI' on review, probably we don't need it now and it's not really related to Data Asset. We will add late in future when we make BT to work properly

2023-01-01 16:23 UTC, JanSeliv commented on Plugins/GameFeatures/NewAI/Source/NewAIRuntime/Private/NewAIAgentComponent.cpp
> +		checkf(BehaviorTree, TEXT("CRITICAL ERROR: %s:'BehaviorTree' is not valid"), *FString(__FUNCTION__));
You can't use 'check' here, it will crash the whole editor if designer does not select BT by mistake.
So, 'ensure' here would be much better, it will show the error message without crashing:
```
if (ensureMsgf(BehaviorTree, TEXT("%s:'BehaviorTree' is not valid"), *FString(__FUNCTION__)))
{
AIControllerInternal->RunBehaviorTree(BehaviorTree);
}
```

2023-01-01 16:23 UTC, JanSeliv commented on Plugins/GameFeatures/NewAI/Source/NewAIRuntime/Private/NewAIAgentComponent.cpp
> +	if (CurrentGameState == ECurrentGameState::GameStarting)
Now, you start BT on GameStarting, while 3-2-1-GO timer. So it makes AI run too early while real players still do not have control. Please put it on In-Game state or remove that code for now

2023-01-01 16:23 UTC, JanSeliv commented on Plugins/GameFeatures/NewAI/Source/NewAIRuntime/Private/NewAIManagerComponent.cpp
> +const UNewAIDataAsset* UNewAIManagerComponent::GetNewAIDataAsset()
Please add comment above

2023-01-01 16:23 UTC, JanSeliv commented on Plugins/GameFeatures/NewAI/Source/NewAIRuntime/Private/NewAIAgentComponent.cpp
> +	       *FString(__FUNCTION__));
Moving FString to new line looks weird, autoformatting?

2023-01-01 16:23 UTC, JanSeliv commented on Plugins/GameFeatures/NewAI/Source/NewAIRuntime/Private/NewAIManagerComponent.cpp
> +	               *FString(__FUNCTION__)))
Moving FString to new line looks weird, autoformatting?

2023-01-01 16:23 UTC, JanSeliv commented on Plugins/GameFeatures/NewAI/Source/NewAIRuntime/Public/NewAIDataAsset.h
> + *
Please add comment

2023-01-01 16:23 UTC, JanSeliv commented on Plugins/GameFeatures/NewAI/Source/NewAIRuntime/Public/NewAIDataAsset.h
> +#include "BehaviorTree/BehaviorTree.h"
Please do not include unnecessary classes right in the headers. Use here class predefinition: add 'class' before 'UBehaviorTree usage'

2023-01-01 16:23 UTC, JanSeliv commented on Plugins/GameFeatures/NewAI/Source/NewAIRuntime/Public/NewAIDataAsset.h
> +#include "CoreMinimal.h"
"CoreMinimal" is unnecessary here, you already have include to DataAsset that substitutes it.

2023-01-01 16:23 UTC, JanSeliv commented on Plugins/GameFeatures/NewAI/Source/NewAIRuntime/Public/NewAIDataAsset.h
> +#include "Engine/DataAsset.h"
Please format it to be like:

Please format it to be like

#include "Engine/DataAsset.h"
//---
#include "NewAIDataAsset.generated.h"

2023-01-01 16:23 UTC, JanSeliv commented on Plugins/GameFeatures/NewAI/Source/NewAIRuntime/Public/NewAIDataAsset.h
> +	TObjectPtr<UBehaviorTree> BehaviorTreeInternal;
Please do not move meta to the new line, keep it on the same with UPROPERTY

2023-01-01 16:23 UTC, JanSeliv commented on Plugins/GameFeatures/NewAI/Source/NewAIRuntime/Public/NewAIDataAsset.h
> +	UPROPERTY(EditAnywhere, BlueprintReadWrite, Transient, Category = "C++",
'Transient' specifier is wrong here, please remove it (rest is fine) because you do WANT to serialize this asset. It means, having it Transient, it will load you null instead of selected asset in the build

2023-01-01 16:23 UTC, JanSeliv commented on Plugins/GameFeatures/NewAI/Source/NewAIRuntime/Public/NewAIDataAsset.h
> +	TObjectPtr<UBehaviorTree> BehaviorTreeInternal;
Please add '= nullptr;' to avoid cooking warning
TObjectPtr<UBehaviorTree> BehaviorTreeInternal = nullptr;

2023-01-01 16:23 UTC, JanSeliv commented on Plugins/GameFeatures/NewAI/Source/NewAIRuntime/Public/NewAIDataAsset.h
> +		meta = (BlueprintProtected, DisplayName = "Behaviour Tree asset"))
'Behaviour' the 'u' is grammar mistake, also 'asset' word is unnecessary here.
So, please replace DisplayName = "Behaviour Tree asset" by:
DisplayName = "Behavior Tree'

2023-01-01 16:23 UTC, JanSeliv commented on Plugins/GameFeatures/NewAI/Source/NewAIRuntime/Public/NewAIManagerComponent.h
> +	meta = (BlueprintSpawnableComponent))
Please do not move meta ever, keep it on the same line with UCLASS

2023-01-01 16:23 UTC, JanSeliv commented on Plugins/GameFeatures/NewAI/Source/NewAIRuntime/Public/NewAIManagerComponent.h
> +		meta = (BlueprintProtected, DisplayName = "NewAI Data Asset", ShowOnlyInnerProperties))
- Do not move meta (the same as comments above)

2023-01-01 16:23 UTC, JanSeliv commented on Plugins/GameFeatures/NewAI/Source/NewAIRuntime/Public/NewAIManagerComponent.h
> +	TObjectPtr<UNewAIDataAsset> NewAIDataAssetInternal;
'ShowOnlyInnerProperties' is unnecessary here, please remove it, it will not expand anything since it's data asset pointer that is set in Details Panel of Manager blueprint

2023-01-01 16:23 UTC, JanSeliv commented on Plugins/GameFeatures/NewAI/Source/NewAIRuntime/Private/NewAIDataAsset.cpp
> +#include "NewAIDataAsset.h"
I assume you can remove this .cpp file since it's empty. We will add If would need it in future

2023-01-01 16:24 UTC, JanSeliv commented
I see, we have '**BB_NewAI**' on review, probably we don't need it now and it's not really related to Data Asset. We will add late in future when we make BT to work properly

2023-01-01 16:25 UTC, JanSeliv commented
> ![image](https://user-images.githubusercontent.com/5227233/210150972-35530fb1-de2e-41c4-aeb6-f001e81ba2c1.png) !
this first image is broken, what is there?

2023-01-01 16:27 UTC, JanSeliv commented
There is 'agent' blueprint in review while there nothing changed, right? (not manager one where you set data asset) Could you please 'revert' the agent blueprint to exclude it from review?

2023-01-01 16:29 UTC, JanSeliv requested changes
Thank you for submitting Data Asset. From the logic perspective everything is pretty cool while I found only minor issues. Please address them first

2023-01-02 20:25 UTC, JanSeliv requested changes

2023-01-02 20:25 UTC, JanSeliv commented on Plugins/GameFeatures/NewAI/Source/NewAIRuntime/Public/NewAIDataAsset.h
> +	FORCEINLINE UBehaviorTree* GetBehaviorTree() const { return BehaviorTreeInternal; }
It does not know anything about UBehaviorTree class here. Please add there 'class' or remove it everywhere and keep 'class UBehaviorTree' between includes and UCLASS on the line 8

2023-01-02 20:25 UTC, JanSeliv commented on Plugins/GameFeatures/NewAI/Source/NewAIRuntime/Public/NewAIManagerComponent.h
> +	TObjectPtr<UNewAIDataAsset> NewAIDataAssetInternal;
Please add '= nullptr;' for every TObjectPtr to avoid cooking warning
TObjectPtr NewAIDataAssetInternal= nullptr;

2023-01-02 21:10 UTC, h4rdmol commented
![image](https://user-images.githubusercontent.com/5227233/210278268-bf3ffe75-e1fd-4a86-8572-26737f065ccd.png)
Reference was somewhy lost in the NewAIDataAsset file.

2023-01-02 21:52 UTC, JanSeliv commented on Plugins/GameFeatures/NewAI/Source/NewAIRuntime/Public/NewAIDataAsset.h
> +	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "C++", meta = (BlueprintProtected, DisplayName = "Behavior Tree"))
please replace 'EditAnywhere, BlueprintReadWrite' by 'EditDefaultsOnly, BlueprintReadOnly' as it it for any Data Asset in game to prevent its editing in blueprints since data should be read-only

2023-01-04 16:34 UTC, merged