Added main menu music depends on chosen level
JanSeliv/Bomber pull request #61
Opened 2023-01-01 17:02 UTC by h4rdmol

### Task: https://trello.com/c/efYeQG84/610-switch-main-menu-background-music-depending-on-level-type

### Description:
Added assets needed for each level main menu. 

### Globals DA_Sounds: 
![image](https://user-images.githubusercontent.com/5227233/210178766-8b4763a4-c376-49f8-83be-d5b7ad6e5b79.png)

### Maya:
![image](https://user-images.githubusercontent.com/5227233/210178776-b1c697b7-8e52-480a-9770-f4c135a6bbc1.png)
![image](https://user-images.githubusercontent.com/5227233/210178792-09d09fe2-e003-4f6b-bb69-7b7e1aff5609.png)
![image](https://user-images.githubusercontent.com/5227233/210178805-5d0ae74b-b2ea-4e77-8439-1f2665dba7b3.png)

### City:
![image](https://user-images.githubusercontent.com/5227233/210178836-24203506-9ffa-4a85-940c-b8e48a9929f6.png)
![image](https://user-images.githubusercontent.com/5227233/210178851-ae2eb3e5-e68c-44da-a9cf-ff1ae5d0e5a1.png)
![image](https://user-images.githubusercontent.com/5227233/210178855-ad47ac0b-ec73-4ef7-bb46-1a388498c221.png)

### Forest:
![image](https://user-images.githubusercontent.com/5227233/210178864-bc06195e-518b-46b5-90a5-12ced5360679.png)
![image](https://user-images.githubusercontent.com/5227233/210178873-48bb8ed4-ae9c-4231-8766-6908876b08ef.png)
![image](https://user-images.githubusercontent.com/5227233/210178880-306ac887-4ffe-4733-86b9-00bd8d51ee7e.png)

### Under Water:
![image](https://user-images.githubusercontent.com/5227233/210178893-35afd323-e060-42d1-8c67-f6f04eb3df37.png)
![image](https://user-images.githubusercontent.com/5227233/210178901-a4ac30b4-d0ef-46ec-9891-054a6c5cc539.png)
![image](https://user-images.githubusercontent.com/5227233/210178903-a3c0cefc-da9d-461c-870c-a11f73025b3e.png)

2023-01-01 17:05 UTC, h4rdmol commented
### Video:
https://user-images.githubusercontent.com/5227233/210179051-4aa3c445-5c66-4738-bb95-d8b03bd199d3.mp4

2023-01-02 01:35 UTC, JanSeliv commented
Right now, for every meta sound asset, you have **'Virtualization Mode'** as 'Restart'. Please set it to be '**Play when silent**', the same as for all other meta sound assets in game. It means, if mute the music volume in game settings and unmute again, the music will not continue. 
image](https://user-images.githubusercontent.com/20540872/210189824-6575aae0-7ba4-4513-813f-b4d5ba0aa938.png)

2023-01-02 01:37 UTC, JanSeliv commented
Please remove MS_MainMenuMusic and SW_MainMenuMusic, it's unused anymore.
I like that original sound and we will consider can we reuse it somewhere else, but it would be another name for these assets

2023-01-02 01:46 UTC, JanSeliv requested changes
Thank you for PR. I did not find anything in code, it's perfect. Please address content changes I asked above

2023-01-02 14:31 UTC, JanSeliv commented on Source/Bomber/Private/Globals/SoundsDataAsset.cpp
> -		return GetMainMenuMusic();
Please remove USoundsDataAsset::GetMainMenuMusic() method and USoundsDataAsset::MainMenuMusicInternal property from code since it is not used anymore after your implementation

2023-01-02 16:22 UTC, h4rdmol commented
Removed the MainMenuMusicInternal 
![image](https://user-images.githubusercontent.com/5227233/210256716-241f7936-1c48-4896-91ca-a466e0bbaf98.png)

### **Settings for meta sounds assets: **

### Maya 
![image](https://user-images.githubusercontent.com/5227233/210256763-e9289385-eb35-4ca5-b222-dd54b54d59e9.png)

### City
![image](https://user-images.githubusercontent.com/5227233/210256793-2bdba41b-ffaf-45a0-8370-bc997f4a7e6f.png)

### Forest
![image](https://user-images.githubusercontent.com/5227233/210256818-73b480dc-8a33-4b48-a918-6d4c4634b243.png)

### Under Water
![image](https://user-images.githubusercontent.com/5227233/210256835-f5b72d24-057f-494d-a844-004a9da3302b.png)

2023-01-02 16:28 UTC, JanSeliv requested changes

2023-01-02 16:28 UTC, JanSeliv commented on Plugins/MetaCheatManager/Binaries/Win64/UnrealEditor.modules
> +		"MetaCheatManager": "UnrealEditor-MetaCheatManager-0002.dll"
Please remove binaries from the review

2023-01-02 16:41 UTC, merged